# 文章的路径
base_dir: /home/rainboy/mycode/pcs-data/_article
#全体上传的时候略过的文件夹或文件名
exclude:
  - ._evil
  - readme.md
  - _drafts
#server_url: http://localhost:3000
server_url: http://pcs.rainboy.cc
key: mytoken
